### PR TITLE
Add CORS support to server.

### PR DESCRIPTION
**Pull request by DViraj**
Useful when running React Native app in different port.

### CODE REVIEW

**Comment by DViraj** [comment]
Seems I missed the part on http://localhost:3000/react. May be this change is not required?

**Comment by am-MongoDB** [comment]
Thanks for the suggestion.

I hit the problem in a development scenario and so the Blog includes instructions to use the CORS Chrome extension if needed. In "production", I've assumed that the REST API and the host serving up the app files would be one and the same and so this wouldn't be needed.

Andrew.

**Comment by DViraj** [comment]
Yep, I missed that part and used this change to make it work.
And yes, it's not good to do this in a production environment.

Viraj

**Comment by ShadSterling** [comment]
It would be fine for production if you replaced "*" with a setting and omitted the headers when unset.

**Pull request closed without merging**
